-- Supabase SQL Seed Script
BEGIN;
INSERT INTO categories (slug, name) VALUES ('backtracking', 'Backtracking') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('big_integer', 'Big Integer') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('bit_manipulation', 'Bit Manipulation') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('ciphers', 'Ciphers') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('compression', 'Compression') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('conversions', 'Conversions') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('data_structures', 'Data Structures') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('data_structures/probabilistic', 'Data Structures/Probabilistic') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('dynamic_programming', 'Dynamic Programming') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('financial', 'Financial') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('general', 'General') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('general/permutations', 'General/Permutations') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('geometry', 'Geometry') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('graph', 'Graph') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('greedy', 'Greedy') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('hashing', 'Hashing') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('machine_learning', 'Machine Learning') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('machine_learning/loss_function', 'Machine Learning/Loss Function') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('machine_learning/optimization', 'Machine Learning/Optimization') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('math', 'Math') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('navigation', 'Navigation') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('number_theory', 'Number Theory') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('searching', 'Searching') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('signal_analysis', 'Signal Analysis') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('sorting', 'Sorting') ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (slug, name) VALUES ('string', 'String') ON CONFLICT (slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'all_combination_of_size_k', 'The All-Star Squad Selection: Combinations of Size K', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'graph_coloring', '5G Tower Frequency Allocation: Graph Coloring', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'hamiltonian_cycle', 'The Traveling Courier: Hamiltonian Cycle', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'knight_tour', 'The Midnight Chess Inspector: Knight''s Tour', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'n_queens', 'The Royal Peace Treaty: N-Queens', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'parentheses_generator', 'Architect''s Balanced Bridges: Parentheses Generator', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'permutations', 'The Vault Pin-Code: Distinct Permutations', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'rat_in_maze', 'Laboratory Cheese Heist: Rat in a Maze', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'subset_sum', 'Cash Register Audit: Subset Sum', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('backtracking', 'sudoku', 'The Locked Grid Vault: Sudoku Solver', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('big_integer', 'fast_factorial', 'Fast Factorial', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('big_integer', 'multiply', 'Multiply', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('big_integer', 'poly1305', 'Poly1305', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'binary_coded_decimal', 'Binary Coded Decimal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'binary_count_trailing_zeros', 'Binary Count Trailing Zeros', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'binary_shifts', 'Binary Shifts', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'counting_bits', 'Counting Bits', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'find_missing_number', 'Find Missing Number', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'find_previous_power_of_two', 'Find Previous Power Of Two', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'find_unique_number', 'Find Unique Number', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'hamming_distance', 'Hamming Distance', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'highest_set_bit', 'Highest Set Bit', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'is_power_of_two', 'Is Power Of Two', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'n_bits_gray_code', 'N Bits Gray Code', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'reverse_bits', 'Reverse Bits', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'rightmost_set_bit', 'Rightmost Set Bit', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'sum_of_two_integers', 'Sum Of Two Integers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'swap_odd_even_bits', 'Swap Odd Even Bits', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('bit_manipulation', 'twos_complement', 'Twos Complement', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'aes', 'Aes', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'affine_cipher', 'Affine Cipher', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'another_rot13', 'Another Rot13', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'baconian_cipher', 'Baconian Cipher', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'base16', 'Base16', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'base32', 'Base32', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'base64', 'Base64', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'base85', 'Base85', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'caesar', 'Caesar', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'chacha', 'Chacha', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'diffie_hellman', 'Diffie Hellman', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'gronsfeld', 'Gronsfeld', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'hill_cipher', 'Hill Cipher', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'kernighan', 'Kernighan', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'morse_code', 'Morse Code', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'polybius', 'Polybius', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'rail_fence', 'Rail Fence', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'rot13', 'Rot13', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'rsa_cipher', 'Rsa Cipher', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'salsa', 'Salsa', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'tea', 'Tea', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'theoretical_rot13', 'Theoretical Rot13', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'transposition', 'Transposition', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'trifid', 'Trifid', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'vernam', 'Vernam', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'vigenere', 'Vigenere', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('ciphers', 'xor', 'Xor', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('compression', 'burrows_wheeler_transform', 'Burrows Wheeler Transform', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('compression', 'huffman_encoding', 'Huffman Encoding', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('compression', 'lz77', 'Lz77', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('compression', 'move_to_front', 'Move To Front', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('compression', 'peak_signal_to_noise_ratio', 'Peak Signal To Noise Ratio', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('compression', 'run_length_encoding', 'Run Length Encoding', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'binary_to_decimal', 'Binary To Decimal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'binary_to_hexadecimal', 'Binary To Hexadecimal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'binary_to_octal', 'Binary To Octal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'decimal_to_binary', 'Decimal To Binary', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'decimal_to_hexadecimal', 'Decimal To Hexadecimal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'decimal_to_octal', 'Decimal To Octal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'energy', 'Energy', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'hexadecimal_to_binary', 'Hexadecimal To Binary', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'hexadecimal_to_decimal', 'Hexadecimal To Decimal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'hexadecimal_to_octal', 'Hexadecimal To Octal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'ipv4_conversion', 'Ipv4 Conversion', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'length_conversion', 'Length Conversion', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'octal_to_binary', 'Octal To Binary', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'octal_to_decimal', 'Octal To Decimal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'octal_to_hexadecimal', 'Octal To Hexadecimal', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'order_of_magnitude_conversion', 'Order Of Magnitude Conversion', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'pressure', 'Pressure', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'rectangular_to_polar', 'Rectangular To Polar', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'rgb_cmyk_conversion', 'Rgb Cmyk Conversion', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'rgb_hsv_conversion', 'Rgb Hsv Conversion', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'roman_numerals', 'Roman Numerals', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'speed', 'Speed', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'temperature', 'Temperature', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'time', 'Time', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'volume', 'Volume', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('conversions', 'weight', 'Weight', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'avl_tree', 'Avl Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'b_tree', 'B Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'binary_search_tree', 'Binary Search Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'fenwick_tree', 'Fenwick Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'floyds_algorithm', 'Floyds Algorithm', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'graph', 'Graph', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'hash_table', 'Hash Table', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'heap', 'Heap', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'lazy_segment_tree', 'Lazy Segment Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'linked_list', 'Linked List', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures/probabilistic', 'bloom_filter', 'Bloom Filter', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures/probabilistic', 'count_min_sketch', 'Count Min Sketch', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'queue', 'Queue', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'range_minimum_query', 'Range Minimum Query', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'rb_tree', 'Rb Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'segment_tree', 'Segment Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'segment_tree_recursive', 'Segment Tree Recursive', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'skip_list', 'Skip List', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'stack_using_singly_linked_list', 'Stack Using Singly Linked List', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'treap', 'Treap', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'trie', 'Trie', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'union_find', 'Union Find', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('data_structures', 'veb_tree', 'Veb Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'catalan_numbers', 'Catalan Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'coin_change', 'Coin Change', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'egg_dropping', 'Egg Dropping', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'fibonacci', 'Fibonacci', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'fractional_knapsack', 'Fractional Knapsack', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'integer_partition', 'Integer Partition', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'is_subsequence', 'Is Subsequence', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'knapsack', 'Knapsack', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'longest_common_subsequence', 'Longest Common Subsequence', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'longest_common_substring', 'Longest Common Substring', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'longest_continuous_increasing_subsequence', 'Longest Continuous Increasing Subsequence', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'longest_increasing_subsequence', 'Longest Increasing Subsequence', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'matrix_chain_multiply', 'Matrix Chain Multiply', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'maximal_square', 'Maximal Square', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'maximum_subarray', 'Maximum Subarray', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'minimum_cost_path', 'Minimum Cost Path', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'optimal_bst', 'Optimal Bst', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'palindrome_partitioning', 'Palindrome Partitioning', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'rod_cutting', 'Rod Cutting', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'smith_waterman', 'Smith Waterman', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'snail', 'Snail', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'subset_generation', 'Subset Generation', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'subset_sum', 'Cash Register Audit: Subset Sum', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'task_assignment', 'Task Assignment', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'trapped_rainwater', 'Trapped Rainwater', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('dynamic_programming', 'word_break', 'Word Break', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'depreciation', 'Depreciation', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'equated_monthly_installments', 'Equated Monthly Installments', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'exponential_moving_average', 'Exponential Moving Average', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'finance_ratios', 'Finance Ratios', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'interest', 'Interest', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'npv', 'Npv', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'npv_sensitivity', 'Npv Sensitivity', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'payback', 'Payback', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'present_value', 'Present Value', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('financial', 'treynor_ratio', 'Treynor Ratio', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'convex_hull', 'Convex Hull', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'fisher_yates_shuffle', 'Fisher Yates Shuffle', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'genetic', 'Genetic', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'hanoi', 'Hanoi', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'huffman_encoding', 'Huffman Encoding', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'kadane_algorithm', 'Kadane Algorithm', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'kmeans', 'Kmeans', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'mex', 'Mex', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general/permutations', 'heap', 'Heap', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general/permutations', 'naive', 'Naive', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general/permutations', 'steinhaus_johnson_trotter', 'Steinhaus Johnson Trotter', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'subarray_sum_equals_k', 'Subarray Sum Equals K', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('general', 'two_sum', 'Two Sum', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('geometry', 'closest_points', 'Closest Points', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('geometry', 'graham_scan', 'Graham Scan', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('geometry', 'jarvis_scan', 'Jarvis Scan', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('geometry', 'point', 'Point', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('geometry', 'polygon_points', 'Polygon Points', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('geometry', 'ramer_douglas_peucker', 'Ramer Douglas Peucker', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('geometry', 'segment', 'Segment', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'ant_colony_optimization', 'Ant Colony Optimization', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'astar', 'Astar', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'bellman_ford', 'Bellman Ford', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'bipartite_matching', 'Bipartite Matching', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'breadth_first_search', 'Breadth First Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'centroid_decomposition', 'Centroid Decomposition', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'decremental_connectivity', 'Decremental Connectivity', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'depth_first_search', 'Depth First Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'depth_first_search_tic_tac_toe', 'Depth First Search Tic Tac Toe', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'detect_cycle', 'Detect Cycle', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'dijkstra', 'Dijkstra', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'dinic_maxflow', 'Dinic Maxflow', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'disjoint_set_union', 'Disjoint Set Union', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'eulerian_path', 'Eulerian Path', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'floyd_warshall', 'Floyd Warshall', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'ford_fulkerson', 'Ford Fulkerson', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'graph_enumeration', 'Graph Enumeration', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'heavy_light_decomposition', 'Heavy Light Decomposition', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'kosaraju', 'Kosaraju', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'lee_breadth_first_search', 'Lee Breadth First Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'lowest_common_ancestor', 'Lowest Common Ancestor', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'minimum_spanning_tree', 'Minimum Spanning Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'page_rank', 'Page Rank', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'prim', 'Prim', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'prufer_code', 'Prufer Code', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'strongly_connected_components', 'Strongly Connected Components', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'tarjans_ssc', 'Tarjans Ssc', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'topological_sort', 'Topological Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('graph', 'two_satisfiability', 'Two Satisfiability', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('greedy', 'job_sequencing', 'Job Sequencing', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('greedy', 'minimum_coin_change', 'Minimum Coin Change', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('greedy', 'smallest_range', 'Smallest Range', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('greedy', 'stable_matching', 'Stable Matching', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('hashing', 'blake2b', 'Blake2B', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('hashing', 'fletcher', 'Fletcher', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('hashing', 'hashing_traits', 'Hashing Traits', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('hashing', 'md5', 'Md5', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('hashing', 'sha1', 'Sha1', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('hashing', 'sha2', 'Sha2', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('hashing', 'sha3', 'Sha3', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'cholesky', 'Cholesky', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'decision_tree', 'Decision Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'k_means', 'K Means', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'k_nearest_neighbors', 'K Nearest Neighbors', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'linear_regression', 'Linear Regression', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'logistic_regression', 'Logistic Regression', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/loss_function', 'average_margin_ranking_loss', 'Average Margin Ranking Loss', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/loss_function', 'hinge_loss', 'Hinge Loss', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/loss_function', 'huber_loss', 'Huber Loss', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/loss_function', 'kl_divergence_loss', 'Kl Divergence Loss', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/loss_function', 'mean_absolute_error_loss', 'Mean Absolute Error Loss', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/loss_function', 'mean_squared_error_loss', 'Mean Squared Error Loss', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/loss_function', 'negative_log_likelihood', 'Negative Log Likelihood', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'naive_bayes', 'Naive Bayes', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/optimization', 'adam', 'Adam', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/optimization', 'gradient_descent', 'Gradient Descent', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning/optimization', 'momentum', 'Momentum', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'perceptron', 'Perceptron', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'principal_component_analysis', 'Principal Component Analysis', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'random_forest', 'Random Forest', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('machine_learning', 'support_vector_classifier', 'Support Vector Classifier', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'abs', 'Abs', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'aliquot_sum', 'Aliquot Sum', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'amicable_numbers', 'Amicable Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'area_of_polygon', 'Area Of Polygon', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'area_under_curve', 'Area Under Curve', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'armstrong_number', 'Armstrong Number', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'average', 'Average', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'baby_step_giant_step', 'Baby Step Giant Step', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'bell_numbers', 'Bell Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'binary_exponentiation', 'Binary Exponentiation', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'binomial_coefficient', 'Binomial Coefficient', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'catalan_numbers', 'Catalan Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'ceil', 'Ceil', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'chinese_remainder_theorem', 'Chinese Remainder Theorem', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'collatz_sequence', 'Collatz Sequence', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'combinations', 'Combinations', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'cross_entropy_loss', 'Cross Entropy Loss', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'decimal_to_fraction', 'Decimal To Fraction', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'doomsday', 'Doomsday', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'elliptic_curve', 'Elliptic Curve', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'euclidean_distance', 'Euclidean Distance', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'exponential_linear_unit', 'Exponential Linear Unit', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'extended_euclidean_algorithm', 'Extended Euclidean Algorithm', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'factorial', 'Factorial', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'factors', 'Factors', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'fast_fourier_transform', 'Fast Fourier Transform', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'fast_power', 'Fast Power', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'faster_perfect_numbers', 'Faster Perfect Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'field', 'Field', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'frizzy_number', 'Frizzy Number', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'gaussian_elimination', 'Gaussian Elimination', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'gaussian_error_linear_unit', 'Gaussian Error Linear Unit', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'gcd_of_n_numbers', 'Gcd Of N Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'geometric_series', 'Geometric Series', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'greatest_common_divisor', 'Greatest Common Divisor', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'huber_loss', 'Huber Loss', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'infix_to_postfix', 'Infix To Postfix', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'interest', 'Interest', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'interpolation', 'Interpolation', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'interquartile_range', 'Interquartile Range', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'karatsuba_multiplication', 'Karatsuba Multiplication', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'lcm_of_n_numbers', 'Lcm Of N Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'leaky_relu', 'Leaky Relu', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'least_square_approx', 'Least Square Approx', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'linear_sieve', 'Linear Sieve', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'logarithm', 'Logarithm', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'lucas_series', 'Lucas Series', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'matrix_ops', 'Matrix Ops', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'mersenne_primes', 'Mersenne Primes', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'miller_rabin', 'Miller Rabin', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'modular_exponential', 'Modular Exponential', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'newton_raphson', 'Newton Raphson', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'nthprime', 'Nthprime', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'pascal_triangle', 'Pascal Triangle', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'perfect_cube', 'Perfect Cube', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'perfect_numbers', 'Perfect Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'perfect_square', 'Perfect Square', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'pollard_rho', 'Pollard Rho', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'postfix_evaluation', 'Postfix Evaluation', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'prime_check', 'Prime Check', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'prime_factors', 'Prime Factors', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'prime_numbers', 'Prime Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'quadratic_residue', 'Quadratic Residue', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'random', 'Random', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'relu', 'Relu', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'sieve_of_eratosthenes', 'Sieve Of Eratosthenes', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'sigmoid', 'Sigmoid', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'signum', 'Signum', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'simpsons_integration', 'Simpsons Integration', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'softmax', 'Softmax', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'sprague_grundy_theorem', 'Sprague Grundy Theorem', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'square_pyramidal_numbers', 'Square Pyramidal Numbers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'square_root', 'Square Root', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'sum_of_digits', 'Sum Of Digits', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'sum_of_geometric_progression', 'Sum Of Geometric Progression', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'sum_of_harmonic_series', 'Sum Of Harmonic Series', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'sylvester_sequence', 'Sylvester Sequence', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'tanh', 'Tanh', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'trapezoidal_integration', 'Trapezoidal Integration', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'trial_division', 'Trial Division', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'trig_functions', 'Trig Functions', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'vector_cross_product', 'Vector Cross Product', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('math', 'zellers_congruence_algorithm', 'Zellers Congruence Algorithm', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('navigation', 'bearing', 'Bearing', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('navigation', 'haversine', 'Haversine', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('navigation', 'rhumbline', 'Rhumbline', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('number_theory', 'compute_totient', 'Compute Totient', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('number_theory', 'euler_totient', 'Euler Totient', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('number_theory', 'kth_factor', 'Kth Factor', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'binary_search', 'The High-Frequency Stock Lookup: Binary Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'binary_search_recursive', 'Binary Search Recursive', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'exponential_search', 'Exponential Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'fibonacci_search', 'Fibonacci Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'interpolation_search', 'Interpolation Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'jump_search', 'Jump Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'kth_smallest', 'Kth Smallest', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'kth_smallest_heap', 'Kth Smallest Heap', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'linear_search', 'Linear Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'moore_voting', 'Moore Voting', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'quick_select', 'Quick Select', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'saddleback_search', 'Saddleback Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'ternary_search', 'Ternary Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'ternary_search_min_max', 'Ternary Search Min Max', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'ternary_search_min_max_recursive', 'Ternary Search Min Max Recursive', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('searching', 'ternary_search_recursive', 'Ternary Search Recursive', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('signal_analysis', 'yin', 'Yin', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'bead_sort', 'Bead Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'binary_insertion_sort', 'Binary Insertion Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'bingo_sort', 'Bingo Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'bitonic_sort', 'Bitonic Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'bogo_sort', 'Bogo Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'bubble_sort', 'The Warehouse Pod Organizer: Bubble Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'bucket_sort', 'Bucket Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'cocktail_shaker_sort', 'Cocktail Shaker Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'comb_sort', 'Comb Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'counting_sort', 'Counting Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'cycle_sort', 'Cycle Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'dutch_national_flag_sort', 'Dutch National Flag Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'exchange_sort', 'Exchange Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'gnome_sort', 'Gnome Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'heap_sort', 'Heap Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'insertion_sort', 'Insertion Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'intro_sort', 'Intro Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'merge_sort', 'Merge Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'odd_even_sort', 'Odd Even Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'pancake_sort', 'Pancake Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'patience_sort', 'Patience Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'pigeonhole_sort', 'Pigeonhole Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'quick_sort', 'Quick Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'quick_sort_3_ways', 'Quick Sort 3 Ways', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'radix_sort', 'Radix Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'selection_sort', 'Selection Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'shell_sort', 'Shell Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'sleep_sort', 'Sleep Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'sort_utils', 'Sort Utils', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'stooge_sort', 'Stooge Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'strand_sort', 'Strand Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'tim_sort', 'Tim Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'tournament_sort', 'Tournament Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'tree_sort', 'Tree Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'wave_sort', 'Wave Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('sorting', 'wiggle_sort', 'Wiggle Sort', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'aho_corasick', 'Aho Corasick', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'anagram', 'Anagram', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'autocomplete_using_trie', 'Autocomplete Using Trie', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'boyer_moore_search', 'Boyer Moore Search', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'burrows_wheeler_transform', 'Burrows Wheeler Transform', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'duval_algorithm', 'Duval Algorithm', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'hamming_distance', 'Hamming Distance', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'isogram', 'Isogram', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'isomorphism', 'Isomorphism', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'jaro_winkler_distance', 'Jaro Winkler Distance', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'knuth_morris_pratt', 'Knuth Morris Pratt', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'levenshtein_distance', 'Levenshtein Distance', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'lipogram', 'Lipogram', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'manacher', 'Manacher', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'palindrome', 'Palindrome', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'pangram', 'Pangram', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'rabin_karp', 'Rabin Karp', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'reverse', 'Reverse', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'run_length_encoding', 'Run Length Encoding', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'shortest_palindrome', 'Shortest Palindrome', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'suffix_array', 'Suffix Array', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'suffix_array_manber_myers', 'Suffix Array Manber Myers', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'suffix_tree', 'Suffix Tree', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
INSERT INTO problems (category_slug, slug, title, difficulty) VALUES ('string', 'z_algorithm', 'Z Algorithm', 'Medium') ON CONFLICT (category_slug, slug) DO NOTHING;
COMMIT;